# Default values for simple_small_api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: andpac/simple_small_api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  #tag: ""

# env:
#   - name: PG_HOST
#     value: "127.0.0.1"
#   - name: PG_PORT
#     value: "5432"
#   - name: PG_USER
#     value: "postgres"
#   - name: PG_PASSWORD
#     value: "somePassword"
#   - name: PG_DB
#     value: "postgres"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

rolling:
  maxUnavailable: 1
  maxSurge: 3
